name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"  # Cron expression to run every 12 hours

  workflow_dispatch:  # Manual trigger

  push:
    branches:
      - main  # Main branch par push hone par workflow chale
      - master  # Master branch par bhi workflow chale

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate snake.svg file
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-light

      # Step 2: Push the generated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # This is the output branch
          build_dir: dist  # dist folder where snake.svg is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Commit and push changes to main and master branches (if required)
      - name: Commit and push to main and master branches
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Update snake.svg"
          git push origin main  # Push to the main branch
          git push origin master  # Push to the master branch
