name: Generate Snake Animation

on:
  schedule: # execute every 12 hours
    - cron: "* */6 * * *"
  workflow_dispatch:  # Trigger manually from GitHub UI
  push:
    branches:
      - master  # Run on push to master

jobs:
  generate:
    permissions:
      contents: write  # Required to push to the output branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Step 1: Generate snake.svg using Platane/snk
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Uses your GitHub username
        # The action automatically creates the snake.svg in the dist/ directory

      # Step 2: Change background color to white
      - name: Modify SVG background color
        run: |
          # Ensure the background color of snake.svg is set to white
          sed -i 's/<svg /<svg style="background-color: white;"/' dist/snake.svg
          # Ensure there is no other conflicting style
          sed -i 's/background-color[^;]*;/background-color: white;/' dist/snake.svg

      # Step 3: Push the generated snake.svg to the output branch
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Target branch to push to
          build_dir: dist         # Directory where the snake.svg is located
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication 
