name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Manual trigger
  push:  # Run on any branch push

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark&color_snake=#3178c6&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
            dist/snake-light.svg?palette=github-light&color_snake=white&color_dots=#f0f0f0,#d1e1f0,#b2c7f7,#a3d2f7,#92c3f6

      - name: Create dist directory if it doesn't exist
        run: mkdir -p dist

      - name: Debug - List generated files
        run: ls -la dist || echo "dist directory is empty or doesn't exist"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Update snake animation from ${{ github.ref_name }} branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
