name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Run every 12 hours
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark&color_snake=blue&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Debug - List generated files
        run: |
          mkdir -p dist
          ls -la dist || echo "dist directory is empty or doesn't exist"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
